package auth

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/Azure/go-autorest/autorest"
	"github.com/Azure/go-autorest/autorest/date"
)

// The package's fully qualified name.
const fqdn = "github.com/qnap/qvs-sdk-for-go/services/auth"

// LoginResponse ...
type LoginResponse struct {
	autorest.Response `json:"-"`
	Status            *int32  `json:"status,omitempty"`
	Data              *User   `json:"data,omitempty"`
	Traceback         *string `json:"traceback,omitempty"`
}

// LogoutResponse ...
type LogoutResponse struct {
	autorest.Response `json:"-"`
	Status            *int32  `json:"status,omitempty"`
	Traceback         *string `json:"traceback,omitempty"`
}

// User ...
type User struct {
	ClearLogTimeLocaltime *date.Time `json:"clear_log_time_localtime,omitempty"`
	Description           *string    `json:"description,omitempty"`
	ID                    *int64     `json:"id,omitempty"`
	IsSuperuser           *bool      `json:"is_superuser,omitempty"`
	LastLoginLocaltime    *date.Time `json:"last_login_localtime,omitempty"`
	Username              *string    `json:"username,omitempty"`
}
