package vms

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// ImportType enumerates the values for import type.
type ImportType string

const (
	// Local ...
	Local ImportType = "local"
	// PC ...
	PC ImportType = "PC"
	// Remote ...
	Remote ImportType = "remote"
)

// PossibleImportTypeValues returns an array of possible values for the ImportType const type.
func PossibleImportTypeValues() []ImportType {
	return []ImportType{Local, PC, Remote}
}

// ImportType1 enumerates the values for import type 1.
type ImportType1 string

const (
	// ImportType1Local ...
	ImportType1Local ImportType1 = "local"
	// ImportType1PC ...
	ImportType1PC ImportType1 = "PC"
	// ImportType1Remote ...
	ImportType1Remote ImportType1 = "remote"
)

// PossibleImportType1Values returns an array of possible values for the ImportType1 const type.
func PossibleImportType1Values() []ImportType1 {
	return []ImportType1{ImportType1Local, ImportType1PC, ImportType1Remote}
}

// Protocol enumerates the values for protocol.
type Protocol string

const (
	// QtsHTTP ...
	QtsHTTP Protocol = "qts_http"
	// QtsHTTPS ...
	QtsHTTPS Protocol = "qts_https"
)

// PossibleProtocolValues returns an array of possible values for the Protocol const type.
func PossibleProtocolValues() []Protocol {
	return []Protocol{QtsHTTP, QtsHTTPS}
}
