package vmsapi

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"context"
	"github.com/qnap/qvs-sdk-for-go/services/vms"
)

// VirtualMachinesClientAPI contains the set of methods on the VirtualMachinesClient type.
type VirtualMachinesClientAPI interface {
	AttachGPU(ctx context.Context, ID int32, data *vms.WritePCISerializer) (result vms.GpuResponse, err error)
	CheckISO(ctx context.Context, body vms.Body) (result vms.CheckIsoResponse, err error)
	Clone(ctx context.Context, ID int32, body string) (result vms.CloneResponse, err error)
	Create(ctx context.Context, data *vms.WriteVMSerializer) (result vms.CreateResponse, err error)
	CreateAutoInstallDevice(ctx context.Context, ID int32, body string) (result vms.CreateAutoInstallDeviceResponse, err error)
	Destroy(ctx context.Context, ID int32, data string) (result vms.DestroyResponse, err error)
	DestroyGPU(ctx context.Context, vmid int32, slotKey string) (result vms.GPUDestroyResponse, err error)
	Export(ctx context.Context, ID int32, body string) (result vms.ExportResponse, err error)
	ForceShutdown(ctx context.Context, ID int32) (result vms.ForceshutdownResponse, err error)
	GetIPs(ctx context.Context, ID int32) (result vms.IpsResponse, err error)
	List(ctx context.Context, syncParameter bool, fromQvscli *bool, detail *bool, pci *bool) (result vms.ListResponse, err error)
	ListStates(ctx context.Context) (result vms.StatesResponse, err error)
	PartialUpdate(ctx context.Context, ID int32, body *vms.WriteVMSerializer) (result vms.PartialUpdateResponse, err error)
	Restart(ctx context.Context, ID int32) (result vms.ResetResponse, err error)
	Resume(ctx context.Context, ID int32, data *vms.Data) (result vms.ResumeResponse, err error)
	Retrieve(ctx context.Context, ID int32) (result vms.RetrieveResponse, err error)
	Shutdown(ctx context.Context, ID int32) (result vms.ShutdownResponse, err error)
	Start(ctx context.Context, ID int32) (result vms.StartResponse, err error)
	StoppingProgress(ctx context.Context) (result vms.StoppingProgressResponse, err error)
	Suspend(ctx context.Context, ID int32) (result vms.SuspendResponse, err error)
	Sync(ctx context.Context, ID int32) (result vms.SyncResponse, err error)
}

var _ VirtualMachinesClientAPI = (*vms.VirtualMachinesClient)(nil)

// ImportsClientAPI contains the set of methods on the ImportsClient type.
type ImportsClientAPI interface {
	Check(ctx context.Context, importCheckParameters *vms.Import) (result vms.ImportCheckResponse, err error)
	Config(ctx context.Context, body vms.ImportConfigRequest) (result vms.ImportConfigResponse, err error)
	Download(ctx context.Context, body vms.BodyModel) (result vms.ImportDownloadResponse, err error)
	DownloadResume(ctx context.Context, body string) (result vms.ImportDownloadResumeResponse, err error)
	Network(ctx context.Context) (result vms.SetObject, err error)
	VM(ctx context.Context, body vms.Import) (result vms.ImportVMResponse, err error)
}

var _ ImportsClientAPI = (*vms.ImportsClient)(nil)

// EnvironmentClientAPI contains the set of methods on the EnvironmentClient type.
type EnvironmentClientAPI interface {
	CreateMAC(ctx context.Context) (result vms.GenerateMacResponse, err error)
}

var _ EnvironmentClientAPI = (*vms.EnvironmentClient)(nil)

// AdaptersClientAPI contains the set of methods on the AdaptersClient type.
type AdaptersClientAPI interface {
	Create(ctx context.Context, vmid int32, data *vms.WriteAdapterSerializer) (result vms.AdapterCreateResponse, err error)
	Destroy(ctx context.Context, vmid int32, ID int32) (result vms.AdapterDestroyResponse, err error)
	List(ctx context.Context, vmid int32) (result vms.AdapterListResponse, err error)
	ListIPs(ctx context.Context, vmid int32, ID int32) (result vms.AdapterIpsResponse, err error)
	Retrieve(ctx context.Context, vmid int32, ID int32) (result vms.AdapterRetrieveResponse, err error)
	Update(ctx context.Context, vmid int32, ID int32, body *vms.WriteAdapterSerializer) (result vms.AdapterPartialUpdateResponse, err error)
}

var _ AdaptersClientAPI = (*vms.AdaptersClient)(nil)

// CDRomsClientAPI contains the set of methods on the CDRomsClient type.
type CDRomsClientAPI interface {
	Create(ctx context.Context, vmid int32, data *vms.WriteCDROMSerializer) (result vms.CDROMCreateResponse, err error)
	Destroy(ctx context.Context, vmid int32, ID int32) (result vms.CDROMDestroyResponse, err error)
	InsertVMDriver(ctx context.Context, vmid int32, ID int32, body *vms.WriteCDROMSerializer) (result vms.CDROMInsertVMDriverResponse, err error)
	List(ctx context.Context, vmid int32) (result vms.CDROMListResponse, err error)
	Retrieve(ctx context.Context, vmid int32, ID int32) (result vms.CDROMRetrieveResponse, err error)
	Update(ctx context.Context, vmid int32, ID int32, body *vms.WriteCDROMSerializer) (result vms.CDROMPartialUpdateResponse, err error)
}

var _ CDRomsClientAPI = (*vms.CDRomsClient)(nil)

// DisksClientAPI contains the set of methods on the DisksClient type.
type DisksClientAPI interface {
	Create(ctx context.Context, vmid int32, data *vms.WriteDiskSerializer) (result vms.DiskCreateResponse, err error)
	Destroy(ctx context.Context, vmid int32, ID int32, data string) (result vms.DiskDestroyResponse, err error)
	List(ctx context.Context, vmid int32) (result vms.DiskListResponse, err error)
	Retrieve(ctx context.Context, vmid int32, ID int32) (result vms.DiskRetrieveResponse, err error)
	Update(ctx context.Context, vmid int32, ID int32, body *vms.WriteDiskSerializer, dryRun *bool) (result vms.DiskPartialUpdateResponse, err error)
}

var _ DisksClientAPI = (*vms.DisksClient)(nil)

// GraphicsClientAPI contains the set of methods on the GraphicsClient type.
type GraphicsClientAPI interface {
	Create(ctx context.Context, vmid int32, data *vms.WriteGraphicSerializer) (result vms.GraphicCreateResponse, err error)
	Destroy(ctx context.Context, vmid int32, ID int32) (result vms.GraphicDestroyResponse, err error)
	List(ctx context.Context, vmid int32) (result vms.GraphicListResponse, err error)
	Retrieve(ctx context.Context, vmid int32, ID int32) (result vms.GraphicRetrieveResponse, err error)
	Update(ctx context.Context, vmid int32, ID int32, body *vms.WriteGraphicSerializer) (result vms.GraphicPartialUpdateResponse, err error)
}

var _ GraphicsClientAPI = (*vms.GraphicsClient)(nil)

// PCIsClientAPI contains the set of methods on the PCIsClient type.
type PCIsClientAPI interface {
	CreateGroup(ctx context.Context, vmid int32, data *vms.PCIGroupSerializer) (result vms.PCIGroupCreateResponse, err error)
	DestroyGroup(ctx context.Context, vmid int32, ID int32) (result vms.PCIGroupDestroyResponse, err error)
	List(ctx context.Context, vmid int32) (result vms.PCIListResponse, err error)
	Retrieve(ctx context.Context, vmid int32, ID int32) (result vms.PCIRetrieveResponse, err error)
}

var _ PCIsClientAPI = (*vms.PCIsClient)(nil)

// SATAControllersClientAPI contains the set of methods on the SATAControllersClient type.
type SATAControllersClientAPI interface {
	Create(ctx context.Context, vmid int32, data *vms.WriteSATAControllerSerializer) (result vms.ATAControllerCreateResponse, err error)
	Destroy(ctx context.Context, vmid int32, ID int32) (result vms.ATAControllerDestroyResponse, err error)
	List(ctx context.Context, vmid int32) (result vms.ATAControllerListResponse, err error)
	Retrieve(ctx context.Context, vmid int32, ID int32) (result vms.ATAControllerRetrieveResponse, err error)
}

var _ SATAControllersClientAPI = (*vms.SATAControllersClient)(nil)

// SerialPortsClientAPI contains the set of methods on the SerialPortsClient type.
type SerialPortsClientAPI interface {
	Attach(ctx context.Context, vmid int32, data *vms.SerialPortSerializerType) (result vms.SerialPortCreateResponse, err error)
	Destroy(ctx context.Context, vmid int32, serialportID int32) (result vms.SerialPortDestroyResponse, err error)
	List(ctx context.Context, vmid int32) (result vms.SerialPortListResponseType, err error)
	Retrieve(ctx context.Context, vmid int32, serialportID int32) (result vms.SerialPortRetrieveResponse, err error)
}

var _ SerialPortsClientAPI = (*vms.SerialPortsClient)(nil)

// SharesClientAPI contains the set of methods on the SharesClient type.
type SharesClientAPI interface {
	Create(ctx context.Context, vmid int32, data *vms.SharelinkSerializer) (result vms.ShareLinkCreateResponse, err error)
	Destroy(ctx context.Context, vmid int32, ID int32) (result vms.ShareLinkDestroyResponse, err error)
	List(ctx context.Context, vmid int32) (result vms.ShareLinkListResponse, err error)
	Retrieve(ctx context.Context, vmid int32, ID int32) (result vms.ShareLinkRetrieveResponse, err error)
	Update(ctx context.Context, vmid int32, ID int32, body *vms.WriteSharelinkSerializer) (result vms.ShareLinkPartialUpdateResponse, err error)
}

var _ SharesClientAPI = (*vms.SharesClient)(nil)

// SnapshotsClientAPI contains the set of methods on the SnapshotsClient type.
type SnapshotsClientAPI interface {
	Create(ctx context.Context, vmid int32, data *vms.WriteSnapshotSerializer) (result vms.SnapshotCreateResponse, err error)
	Destroy(ctx context.Context, vmid int32, ID int32) (result vms.SnapshotDestroyResponse, err error)
	List(ctx context.Context, vmid int32) (result vms.SnapshotListResponse, err error)
	Lock(ctx context.Context, vmid int32, ID int32) (result vms.SetObject, err error)
	Retrieve(ctx context.Context, vmid int32, ID int32) (result vms.SnapshotRetrieveResponse, err error)
	Revert(ctx context.Context, vmid int32, ID int32, data *vms.Data) (result vms.SetObject, err error)
}

var _ SnapshotsClientAPI = (*vms.SnapshotsClient)(nil)

// USBsClientAPI contains the set of methods on the USBsClient type.
type USBsClientAPI interface {
	Create(ctx context.Context, vmid int32, data *vms.WriteUSBSerializer) (result vms.USBCreateResponse, err error)
	Destroy(ctx context.Context, vmid int32, ID int32) (result vms.USBDestroyResponse, err error)
	List(ctx context.Context, vmid int32) (result vms.USBListResponse, err error)
	Retrieve(ctx context.Context, vmid int32, ID int32) (result vms.USBRetrieveResponse, err error)
	Update(ctx context.Context, vmid int32, ID int32, body *vms.WriteUSBSerializer) (result vms.USBPartialUpdateResponse, err error)
}

var _ USBsClientAPI = (*vms.USBsClient)(nil)

// VNCTokensClientAPI contains the set of methods on the VNCTokensClient type.
type VNCTokensClientAPI interface {
	Create(ctx context.Context, vmid int32, data string) (result vms.VNCTokenCreateResponse, err error)
	GetIPByAgent(ctx context.Context, vmid int32) (result vms.SetObject, err error)
	List(ctx context.Context, vmid int32) (result vms.VNCTokenListResponse, err error)
}

var _ VNCTokensClientAPI = (*vms.VNCTokensClient)(nil)
