package authapi

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"context"
	"github.com/qnap/qvs-sdk-for-go/services/auth"
)

// ClientAPI contains the set of methods on the Client type.
type ClientAPI interface {
	Login(ctx context.Context, username string, password string) (result auth.LoginResponse, err error)
	Logout(ctx context.Context) (result auth.LogoutResponse, err error)
}

var _ ClientAPI = (*auth.Client)(nil)
