package users

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/Azure/go-autorest/autorest"
	"github.com/Azure/go-autorest/autorest/date"
)

// The package's fully qualified name.
const fqdn = "github.com/qnap/qvs-sdk-for-go/services/users"

// CreateResponse ...
type CreateResponse struct {
	autorest.Response `json:"-"`
	Data              *User  `json:"data,omitempty"`
	Status            *int32 `json:"status,omitempty"`
}

// CreateVMPermissionResponse ...
type CreateVMPermissionResponse struct {
	autorest.Response `json:"-"`
	Data              *VMPermission `json:"data,omitempty"`
	Status            *int32        `json:"status,omitempty"`
}

// DeleteVMPermissionResponse ...
type DeleteVMPermissionResponse struct {
	autorest.Response `json:"-"`
	Status            *int32 `json:"status,omitempty"`
}

// DestroyResponse ...
type DestroyResponse struct {
	autorest.Response `json:"-"`
	Status            *int32 `json:"status,omitempty"`
}

// GetCurrentUserInfoResponse ...
type GetCurrentUserInfoResponse struct {
	autorest.Response `json:"-"`
	Data              *User  `json:"data,omitempty"`
	Status            *int32 `json:"status,omitempty"`
}

// ListResponse ...
type ListResponse struct {
	autorest.Response `json:"-"`
	Data              *[]User `json:"data,omitempty"`
	Status            *int32  `json:"status,omitempty"`
}

// RetrieveResponse ...
type RetrieveResponse struct {
	autorest.Response `json:"-"`
	Data              *User  `json:"data,omitempty"`
	Status            *int32 `json:"status,omitempty"`
}

// UpdateClearLogTimeResponse ...
type UpdateClearLogTimeResponse struct {
	autorest.Response `json:"-"`
	Status            *int32 `json:"status,omitempty"`
}

// UpdateResponse ...
type UpdateResponse struct {
	autorest.Response `json:"-"`
	Data              *User  `json:"data,omitempty"`
	Status            *int32 `json:"status,omitempty"`
}

// UpdateVMPermissionResponse ...
type UpdateVMPermissionResponse struct {
	autorest.Response `json:"-"`
	Data              *VMPermission `json:"data,omitempty"`
	Status            *int32        `json:"status,omitempty"`
}

// User ...
type User struct {
	ClearLogTimeLocaltime *date.Time `json:"clear_log_time_localtime,omitempty"`
	Description           *string    `json:"description,omitempty"`
	ID                    *int32     `json:"id,omitempty"`
	IsSuperuser           *bool      `json:"is_superuser,omitempty"`
	LastLoginLocaltime    *date.Time `json:"last_login_localtime,omitempty"`
	Username              *string    `json:"username,omitempty"`
}

// VMPermission ...
type VMPermission struct {
	ID          *int32    `json:"id,omitempty"`
	VMID        *int32    `json:"vm_id,omitempty"`
	UserID      *int32    `json:"user_id,omitempty"`
	Permissions *[]string `json:"permissions,omitempty"`
}

// VMPermissionBase ...
type VMPermissionBase struct {
	VMID        *int32    `json:"vm_id,omitempty"`
	UserID      *int32    `json:"user_id,omitempty"`
	Permissions *[]string `json:"permissions,omitempty"`
}

// VMPermissionResponse ...
type VMPermissionResponse struct {
	autorest.Response `json:"-"`
	Data              *VMPermission `json:"data,omitempty"`
	Status            *int32        `json:"status,omitempty"`
}

// WriteUser ...
type WriteUser struct {
	Description *string `json:"description,omitempty"`
	IsSuperuser *bool   `json:"is_superuser,omitempty"`
	Password    *string `json:"password,omitempty"`
	Username    *string `json:"username,omitempty"`
}
